### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by coolbix** [dinhduongha/bamboomodules#1]
I've got errors for Bamboo.Core as follows;

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'ISampleAppService' could not be found (are you missing a using directive or an assembly reference?)	Bamboo.Core.HttpApi.Client.ConsoleTestApp	D:\odoo-projects\bamboomodules\services\core\test\Bamboo.Core.HttpApi.Client.ConsoleTestApp\ClientDemoService.cs	14	Active

**Comment by dinhduongha** [comment]
@coolbix 
You can comment out ISampleAppService.
Next version I will remove it.

**Comment by coolbix** [comment]
Thank you.
