### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by coolbix** [dinhduongha/bamboomodules#2]
Errors for Bamboo.Admin;

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Warning As Error: Detected package downgrade: Volo.Abp.AspNetCore.MultiTenancy from 7.2.2 to 7.2.1. Reference the package directly from the project to select a different version. 
 Bamboo.Admin.HttpApi.Host -> Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonXLite 2.2.1 -> Volo.Abp.AspNetCore.Mvc.UI.MultiTenancy 7.2.2 -> Volo.Abp.AspNetCore.MultiTenancy (>= 7.2.2) 
 Bamboo.Admin.HttpApi.Host -> Volo.Abp.AspNetCore.MultiTenancy (>= 7.2.1)	Bamboo.Admin.HttpApi.Host	D:\odoo-projects\bamboomodules\services\admin\Bamboo.Admin\src\Bamboo.Admin.HttpApi.Host\Bamboo.Admin.HttpApi.Host.csproj	1	
Error	MSB3030	Could not copy the file "D:\odoo-projects\bamboomodules\services\admin\Bamboo.Admin\src\Bamboo.Admin.DbMigrator\appsettings.secrets.json" because it was not found.	Bamboo.Admin.DbMigrator	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5181	
Error	MSB3030	Could not copy the file "D:\odoo-projects\bamboomodules\services\admin\Bamboo.Admin\test\Bamboo.Admin.HttpApi.Client.ConsoleTestApp\appsettings.secrets.json" because it was not found.	Bamboo.Admin.HttpApi.Client.ConsoleTestApp	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	5181

**Comment by dinhduongha** [comment]
@coolbix 
1. Fixed. Use LeptonXLite 2.2.0
2. Create file Bamboo.Admin.HttpApi.Client.ConsoleTestApp\appsettings.secrets.json with content `{}` . You may read Microsoft document to known how to use appsettings.secrets.json.

**Comment by coolbix** [comment]
Thank you.
